config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard/index'
  end

  namespace :admin do
    resources :posts
    resources :comments
  end

  resources :articles
  resources :likes
  resources :comments
  post '/preview', to: 'admin/posts#preview'
  post '/photos', to: 'photos#create'
  post '/main_photo', to: 'main_photo#create'

  post '/search', to: 'articles#search'
  get  '/search', to: 'articles#search'

  post '/signin', to: 'admin/sessions#create'
  get '/signin', to: 'admin/sessions#new'
  get '/signout', to: 'admin/sessions#destroy'

  get '/admin', to: 'admin/dashboard#index'

  get '/blog/rss', to: 'welcome#rss'
  get '/about', to: 'welcome#about'
  get '/team', to: 'welcome#team'
  get '/history', to: 'welcome#history'
  get '/contact', to: 'welcome#contact'
  get '/press', to: 'welcome#press'
  get '/photo', to: 'welcome#photo'
  get '/all', to: 'articles#index'
  root 'welcome#index'
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'

  before_action do
    unless login?
      flash[:error] = '请先登录后再操作'
      redirect_to signin_path
    end
  end

  def preview
    html = Markdown.new(params[:body]).to_html
    render text: html
  end

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def edit
    @article = Article.find(params[:id])
    @main_photo = @article.main_photo
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    photo = MainPhoto.find(params[:main_photo_id])
    if check_main_photo_multiple(@article.main_photo, photo)
      @article.main_photo.destroy
      photo.update(article_id: @article.id)
    end
    redirect_to @article
  end

  def new
    @article = Article.new
    @main_photo = MainPhoto.new
  end

  def show
  end

  def create
    @article = Article.new(article_params)
    @main_photo = MainPhoto.where(id: params[:main_photo_id]).first
    if check_main_photo_validate(@main_photo)
      flash.now[:error] = '封面无效, 请重新上传'
      render :new
      return
    end

    if @article.save
      @main_photo.update(article_id: @article.id)
      redirect_to @article
    else
      flash.now[:error] = '新增文章失败: 内容或标题错误'
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_posts_path
  end

  private
  def check_main_photo_multiple(before_photo, after_photo)
    before_photo.id != after_photo.id
  end

  def check_main_photo_validate(photo)
    photo.blank? || photo.article.present?
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= render 'message/flash' %>
<%= form_for @article, url: @article.new_record? ? admin_posts_path : admin_post_path, method: @article.new_record? ? :post : :patch do |f| %>
  <%= hidden_field_tag 'main_photo_id', @main_photo.try(:id) %>
  <p class='article-title'>
    <%= f.label '标题' %><br>
    <%= f.text_field :title %>
  </p>
  <p class='article-photo'>
    <%= f.label '封面' %>
    <a href='#' id='upload-main-photo'>上传</a>
    <input type='file' class='file-main-photo'>
    <% unless ! @main_photo || @main_photo.new_record? %>
      <%= image_tag(@main_photo.image.url, class: 'show-main-photo') %>
    <% end %>
  </p>
  <div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
      <li class='content-title active'><%= link_to '内容', '#' %></li>
      <li class="preview-title"><%= link_to '预览', '#' %></li>
      <a href="#" class='pull-right' id="upload-photo">插入图片</a>
      <input type='file' class='file-window'>
    </ul>
    <%= f.text_area :content %>
    <div class='markdown-body'></div>
  </div>
  <p>
    <%= f.submit '发表' %>
  </p>
<% end %>

app/views/admin/posts/edit.html.erb
<h2 class='article-new'>编辑博客</h2>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h3>所有文章</h3>
<table class="table">
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article %></td>
      <td><%= article.data_time %></td>
      <td>喜欢(<%= article.liked_count %>)</td>
      <td><%= link_to "评论(#{article.comments.size})", admin_comments_path(article_id: article.id) %></td>
      <td><%= link_to "编辑", edit_admin_post_path(article) %></td>
      <td><%= link_to "删除", admin_post_path(article), method: :delete, data: { confirm: "确认删除?" } %></td>
    </tr>
  <% end %>
</table>

app/views/admin/posts/new.html.erb
<h2 class='article-new'>新建文章</h2>
<%= render 'form' %>