config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard/index'
  end

  namespace :admin do
    resources :posts
    resources :comments
  end

  resources :articles
  resources :likes
  resources :comments
  post '/preview', to: 'admin/posts#preview'
  post '/photos', to: 'photos#create'
  post '/main_photo', to: 'main_photo#create'

  post '/search', to: 'articles#search'
  get  '/search', to: 'articles#search'

  post '/signin', to: 'admin/sessions#create'
  get '/signin', to: 'admin/sessions#new'
  get '/signout', to: 'admin/sessions#destroy'

  get '/admin', to: 'admin/dashboard#index'

  get '/blog/rss', to: 'welcome#rss'
  get '/about', to: 'welcome#about'
  get '/team', to: 'welcome#team'
  get '/history', to: 'welcome#history'
  get '/contact', to: 'welcome#contact'
  get '/press', to: 'welcome#press'
  get '/photo', to: 'welcome#photo'
  get '/all', to: 'articles#index'
  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :main_photo, dependent: :destroy

  validates :title, :content, presence: true

  max_paginates_per 100

  def liked_count
    self.likes.size
  end

  def comments_count
    self.comments.size
  end

  def data_time
    self.created_at.strftime("%Y-%m-%d")
  end

  def data_time_cn
    self.created_at.strftime("%m月%d号")
  end

  def truncate_content
    html = HTML_Truncator.truncate(content, 300, length_in_chars: true, keepImageTag: true)
  end

  def filter_content_image
    markdown = markdown_html
    content = markdown.gsub(/<img[^>]+>/, '')
  end

  def filter_content_image_to_markdown
    content = filter_content_image
    content = HTML_Truncator.truncate(content, 300, length_in_chars: true)
  end

  def markdown_html
    Markdown.new(content).to_html
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :message, :username, :email, presence: true
  validates :username, length: { maximum: 20 }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  def data_time
    self.created_at.strftime("%Y-%m-%d %H:%M")
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :article
end

app/models/main_photo.rb
class MainPhoto < ActiveRecord::Base
  belongs_to :article

  mount_uploader :image, ImageUploader
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'

  before_action do
    unless login?
      flash[:error] = '请先登录后再操作'
      redirect_to signin_path
    end
  end

  def index
    @article = Article.find(params[:article_id])
    @comments = @article.comments.order(created_at: :desc)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.destroy
      flash[:notice] = '删除评论成功'
      redirect_to admin_comments_path(article_id: @article)
    else
      flash[:error] = '删除评论失败'
      redirect_to admin_comments_path(article_id: @article)
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'

  before_action do
    unless login?
      flash[:error] = '请先登录后再操作'
      redirect_to signin_path
    end
  end

  def preview
    html = Markdown.new(params[:body]).to_html
    render text: html
  end

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def edit
    @article = Article.find(params[:id])
    @main_photo = @article.main_photo
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    photo = MainPhoto.find(params[:main_photo_id])
    if check_main_photo_multiple(@article.main_photo, photo)
      @article.main_photo.destroy
      photo.update(article_id: @article.id)
    end
    redirect_to @article
  end

  def new
    @article = Article.new
    @main_photo = MainPhoto.new
  end

  def show
  end

  def create
    @article = Article.new(article_params)
    @main_photo = MainPhoto.where(id: params[:main_photo_id]).first
    if check_main_photo_validate(@main_photo)
      flash.now[:error] = '封面无效, 请重新上传'
      render :new
      return
    end

    if @article.save
      @main_photo.update(article_id: @article.id)
      redirect_to @article
    else
      flash.now[:error] = '新增文章失败: 内容或标题错误'
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_posts_path
  end

  private
  def check_main_photo_multiple(before_photo, after_photo)
    before_photo.id != after_photo.id
  end

  def check_main_photo_validate(photo)
    photo.blank? || photo.article.present?
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    @newest_articles = Article.order(created_at: :desc)
    if @newest_articles.size > 20
      @newest_articles[0..20]
    else
      @newest_articles
    end
  end

  helper_method :login?
  def login?
    session[:login].present?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    params[:page] = 1 if params[:page].blank?
    @articles = Article.order(created_at: :desc).page(params[:page]).per(10)
    flash.now[:notice] = '暂时没有数据' if @articles.blank?
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    render :layout => 'show_articles'
  end

  def search
    @articles = Article.where("title like ? OR content like ?", "%#{params[:q]}%", "%#{params[:q]}%").order(created_at: :desc).page(params[:page]).per(10)
    if @articles.blank?
      flash.now[:error] = '没有你要找的内容'
      return
    end

    @articles.map do |a|
      a.title = a.title.gsub(params[:q].to_s, "<em>#{params[:q]}</em>")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout 'show_articles'

  def create
    @comment = Comment.new(comment_params.merge(article_id: params[:article_id]))
    cookies[:username] = @comment[:username]
    cookies[:email] = @comment[:email]

    if @comment.save
      @success = true
      flash.now[:notice] = '添加评论成功'
    else
      @success = false
      flash.now[:error] = '添加评论失败'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:message, :username, :email)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  layout false

  def create
    article = Article.find(params[:article_id])
    like = Like.new(:article_id => article.id)
    if like.save
      render :json => { success: true, id: like.id, count: article.reload.liked_count }
    else
      render :json => { success: false, count: article.reload.liked_count }
    end
  end

  def destroy
    like = Like.find(params[:id])
    article = like.article
    if like.destroy
      render :json => { success: true, count: article.reload.liked_count }
    else
      render :json => { success: false, count: article.reload.liked_count }
    end
  end
end

app/controllers/main_photo_controller.rb
class MainPhotoController < ApplicationController
  def create
    @mainphoto = MainPhoto.new(image: params["Filedata"])
    @mainphoto.save!
    render json: { :img => @mainphoto.image.url, :photo_id => @mainphoto.id }
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(image: params["Filedata"])
    @photo.save!
    render :text=> "![](#{@photo.image.url})"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    params[:page] = 1 if params[:page].blank?
    @articles = Article.order(created_at: :desc).page(params[:page]).per(5)
    flash.now[:notice] = '还没有内容' if @articles.blank?
    render :layout => 'have_background_image'
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_background_image.html.erb
<div class='container home-container home-background-img <%= "home-background-img#{rand(1..3)}" %>'>
  <div class='intro-heading'>
    <div class='row'>
      <div class='small-12 columns'>
        <h1 class='logo'>EXPLORE CREATE SHARE</h1>
        <a class='circle' href='#home'>
          <span class='glyphicon glyphicon-menu-down' aria-hidden="true"></span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_comments.html.erb
<div class='comments-warp'>
  <div class='create-comment'>
    <div class='container'>
      <div class='row'>
        <div class='form-group', id='comments_form_group'>
          <% @comments.each_with_index do |comment, index| %>
              <p class='name'>
                <%= comment.username %>  •
                <span class='created-at'><%= comment.data_time %></span>
              </p>
              <p class='comment-content'>
                <%= comment.message %>
              </p>
          <% end %>
        </div>
        <div id='flash_message'></div>
        <%= form_for Comment.new, url: comments_path(article_id: @article.id), remote: true do |f| %>
          <div class='form-group'>
            <%= f.text_area :message, rows: '3', class: 'form-control', placeholder: '留言...' %>
          </div>
          <div class='form-group'>
            <%= f.text_field :username, value: cookies[:username], class: 'form-control form-comment', placeholder: '你的名字' %>
          </div>
          <div class='form-group'>
            <%= f.text_field :email, value: cookies[:email], class: 'form-control form-comment', placeholder: '邮箱' %>
          </div>
          <div class='form-group'>
            <%= f.submit '发表', class: 'btn btn-default btn-rounded', id: 'form-comment_submit' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class='page-footer'>
  <div>
    <span class='link'>发现.创造.分享</span>
    <span class='time'>© E.C.S.2014 - 2015</span>
  </div>
  <div class='license'>
    <span>
      <a href='http://liuzhen.me' target='_blank'>BUILT BY LIUZHEN</a>
    </span>
  </div>
</div>

app/views/layouts/_navbar_warpper.html.erb
<nav class="navbar navbar-default template-navbar">
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div id='home'></div>
  <div class="container">
    <div class="collapse navbar-collapse navbar-title" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav home-title">
        <li><%= link_to '主页', '/' %></li>
        <li><%= link_to '所有', '/all' %></li>
        <li><%= link_to '关于', '/about', class: 'home-title-about' %></li>
        <li class='home-title-li'><%= link_to '团队', '/team' %></li>
        <li class='home-title-li'><%= link_to '历史', '/history' %></li>
        <li class='home-title-li'><%= link_to '媒体', '/press' %></li>
        <li class='home-title-li'><%= link_to '加入', '/contact' %></li>
      </ul>
      <ul class="nav navbar-nav nav-search">
        <li class='nav-search-li hidden-xs'>
        <%= form_for(:search, url: '/search', method: 'get',  html: { class: 'form-search'} ) do |f| %>
            <span class="glyphicon glyphicon-search btn-search" aria-hidden="true"></span>
            <div class='form-group-search-div'>
              <input class='form-control-search-input' name='q' type='text' value placeholder='搜索'>
            </div>
            <span class='glyphicon glyphicon-remove btn-close' aria-hidden='true'></span>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav nav-default-display-none">
        <li><%= link_to '关于', '/about'%></li>
        <li><%= link_to '团队', '/team' %></li>
        <li><%= link_to '历史', '/history' %></li>
        <li><%= link_to '媒体', '/press' %></li>
        <li><%= link_to '加入', '/contact' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
<title>SZEXPLORE CREATE SHARE</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse rina-admin-navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class='navbar-brand rina-logo' href="/admin">ECSSZ</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/admin/posts/new">创建文章</a></li>
        <li><a href="/admin/posts">文章管理</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">返回首页</a></li>
        <% if login? %>
          <li><a href="/signout">退出</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class='container'>
  <div class='row'>
    <%= yield %>
  </div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SZ EXPLORE CREATE SHARE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id='template-body'>
  <%= render 'layouts/navbar_warpper' %>
  <div class='container'>
    <div class='row'>
        <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/have_background_image.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SZ EXPLORE CREATE SHARE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id='template-body'>
  <%= render 'layouts/background_image' %>
  <%= render 'layouts/navbar_warpper' %>
  <div class='container'>
    <div class='row'>
        <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/show_articles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SZ EXPLORE CREATE SHARE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maxminium-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id='template-body'>
  <%= render 'layouts/navbar_warpper' %>
  <div class='container'>
    <div class='row'>
        <%= yield %>
    </div>
  </div>
  <%= render 'layouts/comments' %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/message/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'error' ? 'danger' : 'info' %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/page/_paginate.erb
<div class='paginate'>
  <%= paginate @articles, :params => { :anchor => 'home' } %>
</div>